#! /bin/sh
### BEGIN INIT INFO
# Provides:          easysoa04
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: EasySOA 0.4 initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Openwide <contact@openwide.fr>
#

# package conf
INSTALL_PATH=/home/axxx/install/easysoa-0.4
SCRIPTNAMEu=run.sh

case "$1" in
  start)
        sudo -u axxx nohup /home/axxx/bin/easysoa04 1>/var/log/easysoa04.log 2> /var/log/easysoa04.err.log &
        ;;
  stop)
        echo Not supported
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

