#! /bin/sh
### BEGIN INIT INFO
# Provides:          jasmine
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tomcat initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Openwide <contact@openwide.fr>
#

# conf
SCRIPTNAME=jasmine

case "$1" in
  start)
        sudo -u axxx nohup /home/axxx/bin/jasmine.sh $@
        ;;
  stop)
        sudo -u axxx nohup /home/axxx/bin/jasmine.sh $@
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

