package com.axxx.dps.apv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-12-03T11:13:37.908+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.axxx.com/dps/apv", name = "PrecomptePartenaireService")
@XmlSeeAlso({ObjectFactory.class})
public interface PrecomptePartenaireService {

    @RequestWrapper(localName = "creerPrecompte", targetNamespace = "http://www.axxx.com/dps/apv", className = "com.axxx.dps.apv.CreerPrecompte")
    @WebMethod
    @ResponseWrapper(localName = "creerPrecompteResponse", targetNamespace = "http://www.axxx.com/dps/apv", className = "com.axxx.dps.apv.CreerPrecompteResponse")
    public void creerPrecompte(
        @WebParam(name = "precomptePartenaire", targetNamespace = "")
        com.axxx.dps.apv.PrecomptePartenaire precomptePartenaire
    );
}
