package com.axxx.dps.apv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-12-03T10:33:43.036+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.axxx.com/dps/apv", name = "ProjetService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjetService {

    @WebResult(name = "success", targetNamespace = "")
    @RequestWrapper(localName = "publish", targetNamespace = "http://www.axxx.com/dps/apv", className = "com.axxx.dps.apv.Publish")
    @WebMethod
    @ResponseWrapper(localName = "publishResponse", targetNamespace = "http://www.axxx.com/dps/apv", className = "com.axxx.dps.apv.PublishResponse")
    public boolean publish(
        @WebParam(name = "projetId", targetNamespace = "")
        java.lang.String projetId
    );
}
